apiVersion: v1
kind: Service
metadata:
  name: my-go-service
spec:
  selector:
    app: my-go-app # This MUST match the label in the deployment
  ports:
    - protocol: TCP
      port: 80         # Internal Cluster Port
      targetPort: 8080 # Port your Go binary listens on
  type: NodePort       # Exposes it to your Mac's IP